CREATE TABLE TB_TELEFONE
(
    id      BIGINT AUTO_INCREMENT NOT NULL,
    apelido VARCHAR(255) NOT NULL,
    numero  INT          NOT NULL,
    ddd     INT          NOT NULL,
    CONSTRAINT pk_tb_telefone PRIMARY KEY (id)
);

CREATE TABLE TB_ENDERECO
(
    id         BIGINT AUTO_INCREMENT NOT NULL,
    logradouro VARCHAR(255) NOT NULL,
    numero     INT          NOT NULL,
    cidade     VARCHAR(255) NOT NULL,
    estado     VARCHAR(255) NOT NULL,
    cep        INT          NOT NULL,
    CONSTRAINT pk_tb_endereco PRIMARY KEY (id)
);

CREATE TABLE TB_QUARTO
(
    id       BIGINT AUTO_INCREMENT NOT NULL,
    numero   INT NOT NULL,
    qtd_cama INT NOT NULL,
    CONSTRAINT pk_tb_quarto PRIMARY KEY (id)
);

CREATE TABLE TB_DIARIAS
(
    id           BIGINT AUTO_INCREMENT NOT NULL,
    data_entrada TIMESTAMP NOT NULL,
    qtd_dias     INT       NOT NULL,
    preco_diaria DECIMAL   NOT NULL,
    CONSTRAINT pk_tb_diarias PRIMARY KEY (id)
);

CREATE TABLE TB_HOTEL
(
    id          BIGINT AUTO_INCREMENT NOT NULL,
    endereco_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_hotel PRIMARY KEY (id)
);

ALTER TABLE TB_HOTEL
    ADD CONSTRAINT FK_TB_HOTEL_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES TB_ENDERECO (id);

CREATE TABLE TB_RESERVA_HOTEL
(
    id              BIGINT AUTO_INCREMENT NOT NULL,
    criacao_reserva TIMESTAMP,
    hotel_id        BIGINT NOT NULL,
    diarias_id      BIGINT NOT NULL,
    CONSTRAINT pk_tb_reserva_hotel PRIMARY KEY (id)
);

ALTER TABLE TB_RESERVA_HOTEL
    ADD CONSTRAINT FK_TB_RESERVA_HOTEL_ON_DIARIAS FOREIGN KEY (diarias_id) REFERENCES TB_DIARIAS (id);

ALTER TABLE TB_RESERVA_HOTEL
    ADD CONSTRAINT FK_TB_RESERVA_HOTEL_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES TB_HOTEL (id);

CREATE TABLE TB_TITULAR
(
    id   BIGINT AUTO_INCREMENT NOT NULL,
    emal VARCHAR(255),
    nome VARCHAR(255),
    cpf  INT,
    CONSTRAINT PK_TB_TITULAR PRIMARY KEY (id)
);

CREATE TABLE TB_PESSOA_TELEFONE
(
    TITULAR_ID  BIGINT NOT NULL,
    TELEFONE_ID BIGINT NOT NULL
);

ALTER TABLE TB_PESSOA_TELEFONE
    ADD CONSTRAINT FK_TB_PESS_TELE_TO_TITULAR FOREIGN KEY (TITULAR_ID) REFERENCES TB_TITULAR (id);

ALTER TABLE TB_PESSOA_TELEFONE
    ADD CONSTRAINT FK_TB_PESS_TELE_TO_TELEFONE FOREIGN KEY (TELEFONE_ID) REFERENCES TB_TELEFONE (id);

CREATE TABLE TB_PESSOA_ENDERECO
(
    TITULAR_ID  BIGINT NOT NULL,
    ENDERECO_ID BIGINT NOT NULL
);

ALTER TABLE TB_PESSOA_ENDERECO
    ADD CONSTRAINT FK_TB_PESS_ENDERECO_TO_TITULAR FOREIGN KEY (TITULAR_ID) REFERENCES TB_TITULAR (id);

ALTER TABLE TB_PESSOA_ENDERECO
    ADD CONSTRAINT FK_TB_PESS_ENDERECO_TO_TELEFONE FOREIGN KEY (ENDERECO_ID) REFERENCES TB_ENDERECO (id);

CREATE TABLE TB_HOTEL_QUARTO
(
    HOTEL_ID  BIGINT NOT NULL,
    QUARTO_ID BIGINT NOT NULL
);

ALTER TABLE TB_HOTEL_QUARTO
    ADD CONSTRAINT FK_TB_HOTEL_QUARTO_TO_HOTEL FOREIGN KEY (HOTEL_ID) REFERENCES TB_HOTEL(id);

ALTER TABLE TB_HOTEL_QUARTO
    ADD CONSTRAINT FK_TB_HOTEL_QUARTO_TO_QUARTO FOREIGN KEY (QUARTO_ID) REFERENCES TB_QUARTO (id);
